### ISSUE TITLE
Retry and report errors during record deletion

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/bibdata#1095]
The current implementation to [delete MARC records from Solr](https://github.com/pulibrary/marc_liberation/pull/1089) uses batches and if there is an error the whole set will fail. 

(1) We should make sure not the entire set of ids fails is there is an error in one batch.

(2) Retry failed batches just once. We don't think we need to reduce the batch size to retry them, but we should retry.

If there any errors we should log that some records could not be deleted even after retrying. This should be sent to HoneyBadger.

**Comment by hackartisan** [comment]
Here's an example of a honeybadger notification: https://github.com/pulibrary/figgy/commit/78717e7a93b90695a453c88ca2744761c68c4a2e

**Comment by hackartisan** [comment]
Example error during a full index run:
```
2021-04-08T10:20:15+00:00 FATAL Unexpected exception Error deleting Solr documents. Status: 510. Body: {
  "error":{
    "metadata":[
      "error-class","org.apache.solr.common.SolrException",
      "root-error-class","org.apache.solr.common.SolrException"],
    "msg":"No active replicas found for collection: catalog-alma-staging2",
    "code":510}}
 when executing #<Traject::Indexer::AfterProcessingStep:0x000055ed351c4030>
2021-04-08T10:20:15+00:00 FATAL Traject::CommandLine: Unexpected exception, terminating execution: #<StandardError: Error deleting Solr documents. Status: 510. Body
: {
  "error":{
    "metadata":[
      "error-class","org.apache.solr.common.SolrException",
      "root-error-class","org.apache.solr.common.SolrException"],
    "msg":"No active replicas found for collection: catalog-alma-staging2",
    "code":510}}
>
/opt/marc_liberation/releases/20210407202025/marc_to_solr/lib/solr_deleter.rb:19:in `block in delete': Error deleting Solr documents. Status: 510. Body: { (StandardError)
  "error":{
    "metadata":[
      "error-class","org.apache.solr.common.SolrException",
      "root-error-class","org.apache.solr.common.SolrException"],
    "msg":"No active replicas found for collection: catalog-alma-staging2",
    "code":510}}
        from /usr/lib/ruby/2.6.0/set.rb:338:in `each_key'
        from /usr/lib/ruby/2.6.0/set.rb:338:in `each'
        from /opt/marc_liberation/releases/20210407202025/marc_to_solr/lib/solr_deleter.rb:17:in `each_slice'
        from /opt/marc_liberation/releases/20210407202025/marc_to_solr/lib/solr_deleter.rb:17:in `delete'
        from marc_to_solr/lib/traject_config.rb:50:in `block (2 levels) in load_config_file'
        from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/traject-2.3.1/lib/traject/indexer/step.rb:177:in `execute'
        from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/traject-2.3.1/lib/traject/indexer.rb:497:in `block in process'
        from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/traject-2.3.1/lib/traject/indexer.rb:495:in `each'
        from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/traject-2.3.1/lib/traject/indexer.rb:495:in `process'
        from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/traject-2.3.1/lib/traject/command_line.rb:67:in `execute'
        from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/traject-2.3.1/bin/traject:14:in `<top (required)>'
        from /opt/marc_liberation/shared/bundle/ruby/2.6.0/bin/traject:23:in `load'
        from /opt/marc_liberation/shared/bundle/ruby/2.6.0/bin/traject:23:in `<main>'
```

**Comment by hackartisan** [comment]
WIP branch https://github.com/pulibrary/bibdata/tree/alma-jrgriffiniii-1095-retry-batch
