### ISSUE TITLE
FATAL Traject::CommandLine: Unexpected exception, terminating execution: #<JSON::GeneratorError: source sequence is illegal/malformed utf-8>

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#1311]
In order to update the index with the latest changes that failed to index I ran liberate:latest. The ids in https://bibdata.princeton.edu/dumps/23793.json were updated but I also noticed an error regarding /malformed utf-8>.

`2021-05-11T12:54:50-04:00 FATAL Traject::CommandLine: Unexpected exception, terminating execution: #<JSON::GeneratorError: source sequence is illegal/malformed utf-8>
/opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/json-1.8.6/lib/json/common.rb:223:in `generate': source sequence is illegal/malformed utf-8 (JSON::GeneratorError)
	from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/json-1.8.6/lib/json/common.rb:223:in `generate'
	from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/traject-2.3.1/lib/traject/solr_json_writer.rb:113:in `send_batch'
	from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/traject-2.3.1/lib/traject/solr_json_writer.rb:104:in `block in put'
	from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/traject-2.3.1/lib/traject/thread_pool.rb:110:in `block in maybe_in_thread_pool'
	from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:363:in `run_task'
	from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `block (3 levels) in create_worker'
	from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `loop'
	from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `block (2 levels) in create_worker'
	from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `catch'
	from /opt/marc_liberation/shared/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block in create_worker'
`

**Comment by christinach** [comment]
Closing - No one reported this error in the alma branch.
