### ISSUE TITLE
Check why https://bibdata.princeton.edu/dumps/209.json keeps failing to index

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#1674]
Bibdata tries to index https://bibdata.princeton.edu/dumps/209.json since 09/22 22:50 at night. As a result the indexing process is pushed back and delayed.

Check datadog for errors
Download and index locally

**Comment by christinach** [comment]
Consistent error:
2021-09-22T22:50:36-04:00 [FATAL] 2438 : Traject::CommandLine: Unexpected exception, terminating execution: #<JSON::GeneratorError: source sequence is illegal/malformed utf-8>
2021-09-22T22:51:21-04:00 [FATAL] 2622 : Traject::CommandLine: Unexpected exception, terminating execution: #<JSON::GeneratorError: source sequence is illegal/malformed utf-8>
2021-09-22T22:52:13-04:00 [FATAL] 2805 : Traject::CommandLine: Unexpected exception, terminating execution: #<JSON::GeneratorError: source sequence is illegal/malformed utf-8>
2021-09-22T23:13:59-04:00 [FATAL] 7910 : Traject::CommandLine: Unexpected exception, terminating execution: #<JSON::GeneratorError: source sequence is illegal/malformed utf-8>
2021-09-23T01:33:46-04:00 [FATAL] 8287 : Traject::CommandLine: Unexpected exception, terminating execution: #<JSON::GeneratorError: source sequence is illegal/malformed utf-8>
2021-09-23T03:23:52-04:00 [FATAL] 1954 : Traject::CommandLine: Unexpected exception, terminating execution: #<JSON::GeneratorError: source sequence is illegal/malformed utf-8>
2021-09-24T00:11:59-04:00 [FATAL] 3385 : Traject::CommandLine: Unexpected exception, terminating execution: #<JSON::GeneratorError: source sequence is illegal/malformed utf-8>
2021-09-25T19:24:56-04:00 [FATAL] 2732 : Traject::CommandLine: Unexpected exception, terminating execution: #<JSON::GeneratorError: source sequence is illegal/malformed utf-8>
2021-09-26T18:38:54-04:00 [FATAL] 10559 : Traject::CommandLine: Unexpected exception, terminating execution: #<JSON::GeneratorError: source sequence is illegal/malformed utf-8>

**Comment by christinach** [comment]
after checking locally:
2021-09-28T05:46:05-04:00 FATAL Traject::CommandLine: Unexpected exception, terminating execution: #<JSON::GeneratorError: source sequence is illegal/malformed utf-8>
Traceback (most recent call last):
	10: from /Users/chortariac/.rvm/gems/ruby-2.6.5/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block in create_worker'
	 9: from /Users/chortariac/.rvm/gems/ruby-2.6.5/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `catch'
	 8: from /Users/chortariac/.rvm/gems/ruby-2.6.5/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `block (2 levels) in create_worker'
	 7: from /Users/chortariac/.rvm/gems/ruby-2.6.5/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `loop'
	 6: from /Users/chortariac/.rvm/gems/ruby-2.6.5/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `block (3 levels) in create_worker'
	 5: from /Users/chortariac/.rvm/gems/ruby-2.6.5/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:363:in `run_task'
	 4: from /Users/chortariac/.rvm/gems/ruby-2.6.5/gems/traject-2.3.1/lib/traject/thread_pool.rb:110:in `block in maybe_in_thread_pool'
	 3: from /Users/chortariac/.rvm/gems/ruby-2.6.5/gems/traject-2.3.1/lib/traject/solr_json_writer.rb:104:in `block in put'
	 2: from /Users/chortariac/.rvm/gems/ruby-2.6.5/gems/traject-2.3.1/lib/traject/solr_json_writer.rb:113:in `send_batch'
	 1: from /Users/chortariac/.rvm/gems/ruby-2.6.5/gems/json-1.8.6/lib/json/common.rb:223:in `generate'
/Users/chortariac/.rvm/gems/ruby-2.6.5/gems/json-1.8.6/lib/json/common.rb:223:in `generate': source sequence is illegal/malformed utf-8 (JSON::GeneratorError)

**Comment by christinach** [comment]
Some records have been indexed and they have a today timestamp, but then it fails with this error and the file will not process successfully. I reproduced the error locally. I also indexed the rest of the records that didnt have a today's timestamp and I assumed that it failed while on this record. 
When I try to index a larger part of the file it fails.

**Comment by christinach** [comment]
We worked with @hectorcorrea in downloading the file and breaking into smaller files to find the record was creating the `source sequence is illegal/malformed utf-8 (JSON::GeneratorError)`. We used https://github.com/hectorcorrea/marcli to break the file in chunks of 100 records, 50s and 10s until we find the record. The record had a bad character in 008 field which we could see only with a hex editor. We decided to remove this record and tar.gz the file and put it back in the box for sidekiq to pick it up again. We forced sidekiq to run the job but it seems that it still keeps in the memory the old file. 
The mms_id that we removed is 99125394551506421.

**Comment by christinach** [comment]
It seems that the second time sidekiq picked it up and indexed it.

**Comment by christinach** [comment]
For example to create chunks of 10 starting from the first record and using the marcli tool:
`./marcli -file read_filename.xml -start=1 -count=10 -format=xml -debug > create_filename_chunks.xml`
We used `xxd filename` to check the hex output.

**Comment by christinach** [comment]
closing this issue. Will open a new one to handle the traject json writer that causes the error.
