### ISSUE TITLE
Removing datadog from ansible causes an http connection error in stgaing

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#1856]
We removed datadog from bibdata staging but we need to clean up some more things with datadog because an error is triggered and prevents indexing when trying to run the rake task to index a file from the console. 
```
E, [2022-05-02T13:07:28.366318 #18118] ERROR -- ddtrace: [ddtrace] (/opt/marc_liberation/shared/bundle/ruby/2.7.0/gems/ddtrace-0.54.2/lib/ddtrace/transport/http/client.rb:37:in `rescue in send_request') Internal error during HTTP transport request. Cause: Failed to open TCP connection to 127.0.0.1:8126 (Connection refused - connect(2) for "127.0.0.1" port 8126) Location: /usr/lib/ruby/2.7.0/net/http.rb:960:in `initialize'
```

**Comment by christinach** [comment]
In the meantime if you need to index a file for testing, use: 

`bundle exec traject -c marc_to_solr/lib/traject_config.rb <path to your file> -u http://lib-solr8-staging.princeton.edu:8983/solr/catalog-staging`

**Comment by christinach** [comment]
with the rails 6.1 upgrade the indexing issue through the rake task was resoved
