### ISSUE TITLE
Update Bundler Config in Bibdata 

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/bibdata#2322]
We need to apply the "bundler fix" to bibdata's environment. 

- [x] Staging
- [x] QA
- [x] Production

## Implementation Notes
[Helpful troubleshooting info](https://github.com/pulibrary/pul-it-handbook/blob/cd2f0ddaf9336764a6501454411e8e9361fe240f/services/passenger.md?plain=1#L8) from the handbook. Errors from a deployment that failed because of bundler referenced in this [issue](https://github.com/pulibrary/bibdata/issues/2282).

**Comment by maxkadel** [comment]
Created a spreadsheet of [versions on bibdata machines](https://docs.google.com/spreadsheets/d/1Z4OziQvRvftJ35RqsjiRld-eNwW3TQ9xRuzWPhD9_dk/edit#gid=0)

**Comment by maxkadel** [comment]
When we try to [preload passenger bundler on production machines](https://github.com/pulibrary/princeton_ansible/pull/4814/files), we get this error:
```
Cannot checkout session because a spawning error occurred. The identifier of the error is 918286ae. Please see earlier logs for details about the error.
App 1564446 output: /usr/local/lib/ruby/site_ruby/3.1.0/rubygems.rb:259:in `find_spec_for_exe':
App 1564446 output: can't find gem bundler (= 2.5.2) with executable bundle (Gem::GemNotFoundException)
App 1564446 output: 	from /usr/local/lib/ruby/site_ruby/3.1.0/rubygems.rb:239:in `bin_path'
App 1564446 output: 	from /usr/local/lib/ruby/site_ruby/3.1.0/bundler/rubygems_integration.rb:151:in `bin_path'
App 1564446 output: 	from /usr/local/lib/ruby/site_ruby/3.1.0/bundler/shared_helpers.rb:321:in `bundle_bin_path'
App 1564446 output: 	from /usr/local/lib/ruby/site_ruby/3.1.0/bundler/shared_helpers.rb:307:in `set_bundle_variables'
App 1564446 output: 	from /usr/local/lib/ruby/site_ruby/3.1.0/bundler/shared_helpers.rb:76:in `set_bundle_environment'
App 1564446 output: 	from /usr/local/lib/ruby/site_ruby/3.1.0/bundler/runtime.rb:20:in `setup'
App 1564446 output: 	from /usr/local/lib/ruby/site_ruby/3.1.0/bundler.rb:162:in `setup'
App 1564446 output: 	from /usr/local/lib/ruby/site_ruby/3.1.0/bundler/setup.rb:26:in `block in <top (required)>'
App 1564446 output: 	from /usr/local/lib/ruby/site_ruby/3.1.0/bundler/ui/shell.rb:159:in `with_level'
App 1564446 output: 	from /usr/local/lib/ruby/site_ruby/3.1.0/bundler/ui/shell.rb:111:in `silence'
App 1564446 output: 	from /usr/local/lib/ruby/site_ruby/3.1.0/bundler/setup.rb:26:in `<top (required)>'
App 1564446 output: 	from <internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
App 1564446 output: 	from <internal:/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
```

**Comment by maxkadel** [comment]
I think we need to run `sudo gem install --default bundle` on the production machines, but we'll need to do so sequentially while they're off the load balancer

**Comment by maxkadel** [comment]
Closed by https://github.com/pulibrary/princeton_ansible/pull/4814
